/* Generated by CIL v. 1.7.0 */
/* print_CIL_Input is false */

enum _1_main_$op;
union _1_main_$node;
struct _IO_FILE;
struct timeval;
extern float strtof(char const   *str , char const   *endptr ) ;
extern void signal(int sig , void *func ) ;
typedef struct _IO_FILE FILE;
extern double strtod(char const   *str , char const   *endptr ) ;
extern int fclose(void *stream ) ;
extern void *fopen(char const   *filename , char const   *mode ) ;
extern void abort() ;
enum _1_main_$op {
    _1_main__local$result_STA_0$value_LIT_0 = 252,
    _1_main__load_long$left_STA_0$result_STA_0 = 94,
    _1_main__constant_long$result_STA_0$value_LIT_0 = 89,
    _1_main__string$result_STA_0$value_LIT_0 = 235,
    _1_main__branchIfTrue$expr_STA_0$label_LAB_0 = 150,
    _1_main__label$label_LAB_0 = 85,
    _1_main__return_int$expr_STA_0 = 34,
    _1_main__call$func_LIT_0 = 58,
    _1_main__convert_void_star2void_star$left_STA_0$result_STA_0 = 239,
    _1_main__constant_int$result_STA_0$value_LIT_0 = 7,
    _1_main__Eq_long_long2int$left_STA_0$result_STA_0$right_STA_1 = 125,
    _1_main__store_void_star$right_STA_0$left_STA_1 = 31,
    _1_main__goto$label_LAB_0 = 55,
    _1_main__store_long$left_STA_0$right_STA_1 = 191
} ;
unsigned char _1_main_$array[1][331]  = { {        _1_main__constant_long$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__store_long$left_STA_0$right_STA_1,        _1_main__constant_long$result_STA_0$value_LIT_0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__store_long$left_STA_0$right_STA_1,        _1_main__constant_long$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)16,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__store_long$left_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)24,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__string$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__convert_void_star2void_star$left_STA_0$result_STA_0, 
            _1_main__store_void_star$right_STA_0$left_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)32,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__store_void_star$right_STA_0$left_STA_1, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)40,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__store_void_star$right_STA_0$left_STA_1,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)48,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)16,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__store_void_star$right_STA_0$left_STA_1,        _1_main__call$func_LIT_0,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__goto$label_LAB_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_long$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__load_long$left_STA_0$result_STA_0,        _1_main__Eq_long_long2int$left_STA_0$result_STA_0$right_STA_1, 
            _1_main__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)9,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__goto$label_LAB_0,        (unsigned char)61,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_long$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)8,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__load_long$left_STA_0$result_STA_0,        _1_main__Eq_long_long2int$left_STA_0$result_STA_0$right_STA_1,        _1_main__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)9, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__goto$label_LAB_0, 
            (unsigned char)35,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_long$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)16,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__load_long$left_STA_0$result_STA_0,        _1_main__Eq_long_long2int$left_STA_0$result_STA_0$right_STA_1, 
            _1_main__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)9,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__goto$label_LAB_0,        (unsigned char)9,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__goto$label_LAB_0,        (unsigned char)146, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__load_long$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)56,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__store_long$left_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)8,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__load_long$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)64,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__store_long$left_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)16,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__load_long$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)72,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__store_long$left_STA_0$right_STA_1,        _1_main__call$func_LIT_0, 
            (unsigned char)2,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)88,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__load_long$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)80, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__store_long$left_STA_0$right_STA_1, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)96,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__string$result_STA_0$value_LIT_0,        (unsigned char)10,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__convert_void_star2void_star$left_STA_0$result_STA_0,        _1_main__store_void_star$right_STA_0$left_STA_1, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)80,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__load_long$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)104, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__store_long$left_STA_0$right_STA_1, 
            _1_main__call$func_LIT_0,        (unsigned char)3,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)112,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__string$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__convert_void_star2void_star$left_STA_0$result_STA_0, 
            _1_main__store_void_star$right_STA_0$left_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)120,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__store_void_star$right_STA_0$left_STA_1, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)128,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__store_void_star$right_STA_0$left_STA_1,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)136,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)16,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__store_void_star$right_STA_0$left_STA_1,        _1_main__call$func_LIT_0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__goto$label_LAB_0, 
            (unsigned char)40,        (unsigned char)255,        (unsigned char)255,        (unsigned char)255, 
            _1_main__goto$label_LAB_0,        (unsigned char)35,        (unsigned char)255,        (unsigned char)255, 
            (unsigned char)255,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__return_int$expr_STA_0}};
long result(long a , long b , long c ) ;
extern void exit(int status ) ;
extern int raise(int sig ) ;
extern int fprintf(struct _IO_FILE *stream , char const   *format  , ...) ;
extern unsigned long strtoul(char const   *str , char const   *endptr , int base ) ;
extern int rand() ;
extern int strncmp(char const   *s1 , char const   *s2 , unsigned long maxlen ) ;
extern int gettimeofday(struct timeval *tv , void *tz  , ...) ;
extern int printf(char const   * __restrict  __format  , ...) ;
int main(void) ;
void megaInit(void) ;
char const   *_1_main_$strings  =    "%ld%ld%ld\000%ld\n\000";
extern unsigned long strlen(char const   *s ) ;
extern long strtol(char const   *str , char const   *endptr , int base ) ;
union _1_main_$node {
   void *_void_star ;
   long _long ;
   int _int ;
};
extern unsigned long strnlen(char const   *s , unsigned long maxlen ) ;
extern void *memcpy(void *s1 , void const   *s2 , unsigned long size ) ;
struct timeval {
   long tv_sec ;
   long tv_usec ;
};
extern void *malloc(unsigned long size ) ;
extern int scanf(char const   * __restrict  __format  , ...)  __asm__("__isoc99_scanf")  ;
void megaInit(void) 
{ 


  {

}
}
int main(void) 
{ 
  char _1_main_$locals[144] ;
  union _1_main_$node _1_main_$stack[1][32] ;
  union _1_main_$node *_1_main_$sp[1] ;
  unsigned char *_1_main_$pc[1] ;

  {
  megaInit();
  _1_main_$sp[0] = _1_main_$stack[0];
  _1_main_$pc[0] = _1_main_$array[0];
  while (1) {
    switch (*(_1_main_$pc[0])) {
    case _1_main__Eq_long_long2int$left_STA_0$result_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_int = (_1_main_$sp[0] + 0)->_long == (_1_main_$sp[0] + -1)->_long;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__local$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_void_star = (void *)(_1_main_$locals + *((int *)_1_main_$pc[0]));
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 4;
    break;
    case _1_main__goto$label_LAB_0: 
    (_1_main_$pc[0]) ++;
    _1_main_$pc[0] += *((int *)_1_main_$pc[0]);
    break;
    case _1_main__call$func_LIT_0: 
    (_1_main_$pc[0]) ++;
    switch (*((int *)_1_main_$pc[0])) {
    case 4: 
    scanf(*((char const   * __restrict  *)(_1_main_$locals + 112)), *((long **)(_1_main_$locals + 120)),
          *((long **)(_1_main_$locals + 128)), *((long **)(_1_main_$locals + 136)));
    break;
    case 1: 
    scanf(*((char const   * __restrict  *)(_1_main_$locals + 24)), *((long **)(_1_main_$locals + 32)),
          *((long **)(_1_main_$locals + 40)), *((long **)(_1_main_$locals + 48)));
    break;
    case 3: 
    printf(*((char const   * __restrict  *)(_1_main_$locals + 96)), *((long *)(_1_main_$locals + 104)));
    break;
    case 2: 
    *((long *)(_1_main_$locals + 88)) = result(*((long *)(_1_main_$locals + 56)),
                                               *((long *)(_1_main_$locals + 64)),
                                               *((long *)(_1_main_$locals + 72)));
    break;
    }
    _1_main_$pc[0] += 4;
    break;
    case _1_main__string$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_void_star = (void *)(_1_main_$strings + *((int *)_1_main_$pc[0]));
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 4;
    break;
    case _1_main__constant_long$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_long = *((long *)_1_main_$pc[0]);
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 8;
    break;
    case _1_main__convert_void_star2void_star$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_void_star = (_1_main_$sp[0] + 0)->_void_star;
    break;
    case _1_main__load_long$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_long = *((long *)(_1_main_$sp[0] + 0)->_void_star);
    break;
    case _1_main__label$label_LAB_0: 
    (_1_main_$pc[0]) ++;
    break;
    case _1_main__branchIfTrue$expr_STA_0$label_LAB_0: 
    (_1_main_$pc[0]) ++;
    if ((_1_main_$sp[0] + 0)->_int) {
      _1_main_$pc[0] += *((int *)_1_main_$pc[0]);
    } else {
      _1_main_$pc[0] += 4;
    }
    (_1_main_$sp[0]) --;
    break;
    case _1_main__constant_int$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_int = *((int *)_1_main_$pc[0]);
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 4;
    break;
    case _1_main__store_void_star$right_STA_0$left_STA_1: 
    (_1_main_$pc[0]) ++;
    *((void **)(_1_main_$sp[0] + -1)->_void_star) = (_1_main_$sp[0] + 0)->_void_star;
    _1_main_$sp[0] += -2;
    break;
    case _1_main__return_int$expr_STA_0: 
    (_1_main_$pc[0]) ++;
    return ((_1_main_$sp[0] + 0)->_int);
    break;
    case _1_main__store_long$left_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    *((long *)(_1_main_$sp[0] + 0)->_void_star) = (_1_main_$sp[0] + -1)->_long;
    _1_main_$sp[0] += -2;
    break;
    }
  }
}
}
long result(long a , long b , long c ) 
{ 
  long remainder ;

  {
  remainder = 1L;
  while (b >= 1L) {
    if (b % 2L == 1L) {
      remainder = (a * remainder) % c;
    }
    a = (a * a) % c;
    b /= 2L;
  }
  return (remainder);
}
}
