/* Generated by CIL v. 1.7.0 */
/* print_CIL_Input is false */

struct _IO_FILE;
enum _1_main_$op;
union _1_main_$node;
struct timeval;
extern void signal(int sig , void *func ) ;
extern float strtof(char const   *str , char const   *endptr ) ;
typedef struct _IO_FILE FILE;
extern double strtod(char const   *str , char const   *endptr ) ;
extern int fclose(void *stream ) ;
int havefun(void) ;
extern void *fopen(char const   *filename , char const   *mode ) ;
void myname_i$nit(void) ;
extern void abort() ;
enum _1_main_$op {
    _1_main__constant_unsigned_int$result_STA_0$value_LIT_0 = 212,
    _1_main__convert_unsigned_int2unsigned_long$left_STA_0$result_STA_0 = 240,
    _1_main__branchIfTrue$expr_STA_0$label_LAB_0 = 125,
    _1_main__constant_void_star$result_STA_0$value_LIT_0 = 132,
    _1_main__Lt_int_int2int$right_STA_0$result_STA_0$left_STA_1 = 15,
    _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1 = 254,
    _1_main__return_int$expr_STA_0 = 34,
    _1_main__load_int$left_STA_0$result_STA_0 = 239,
    _1_main__load_unsigned_int$left_STA_0$result_STA_0 = 105,
    _1_main__PlusA_unsigned_int_unsigned_int2unsigned_int$right_STA_0$result_STA_0$left_STA_1 = 241,
    _1_main__PlusA_int_int2int$left_STA_0$result_STA_0$right_STA_1 = 252,
    _1_main__label$label_LAB_0 = 85,
    _1_main__store_unsigned_int$left_STA_0$right_STA_1 = 33,
    _1_main__MinusA_int_int2int$left_STA_0$result_STA_0$right_STA_1 = 233,
    _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1 = 60,
    _1_main__Eq_int_int2int$right_STA_0$result_STA_0$left_STA_1 = 22,
    _1_main__Ge_unsigned_int_unsigned_int2int$right_STA_0$result_STA_0$left_STA_1 = 124,
    _1_main__constant_int$result_STA_0$value_LIT_0 = 7,
    _1_main__Gt_int_int2int$left_STA_0$result_STA_0$right_STA_1 = 89,
    _1_main__store_int$left_STA_0$right_STA_1 = 58,
    _1_main__string$result_STA_0$value_LIT_0 = 150,
    _1_main__call$func_LIT_0 = 235,
    _1_main__goto$label_LAB_0 = 55,
    _1_main__Mod_int_int2int$left_STA_0$result_STA_0$right_STA_1 = 137,
    _1_main__convert_void_star2void_star$left_STA_0$result_STA_0 = 94,
    _1_main__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1 = 175,
    _1_main__constant_unsigned_long$result_STA_0$value_LIT_0 = 214,
    _1_main__convert_int2unsigned_long$left_STA_0$result_STA_0 = 108,
    _1_main__store_void_star$left_STA_0$right_STA_1 = 191,
    _1_main__local$result_STA_0$value_LIT_0 = 31
} ;
unsigned char _1_main_$array[1][801]  = { {        _1_main__string$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__convert_void_star2void_star$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__store_void_star$left_STA_0$right_STA_1, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)16,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__store_void_star$left_STA_0$right_STA_1,        _1_main__call$func_LIT_0, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)20,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__store_int$left_STA_0$right_STA_1,        _1_main__goto$label_LAB_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)20,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)16, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0, 
            _1_main__Lt_int_int2int$right_STA_0$result_STA_0$left_STA_1,        _1_main__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)14,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__goto$label_LAB_0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__goto$label_LAB_0, 
            (unsigned char)215,        (unsigned char)2,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)24,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_void_star$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1, 
            _1_main__store_int$left_STA_0$right_STA_1,        _1_main__constant_unsigned_int$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)168, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        _1_main__store_unsigned_int$left_STA_0$right_STA_1, 
            _1_main__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)168,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        _1_main__load_unsigned_int$left_STA_0$result_STA_0,        _1_main__constant_unsigned_int$result_STA_0$value_LIT_0, 
            (unsigned char)100,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__Ge_unsigned_int_unsigned_int2int$right_STA_0$result_STA_0$left_STA_1,        _1_main__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)9,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__goto$label_LAB_0,        (unsigned char)9, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__goto$label_LAB_0, 
            (unsigned char)71,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)24,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_void_star$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)168,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            _1_main__load_unsigned_int$left_STA_0$result_STA_0,        _1_main__convert_unsigned_int2unsigned_long$left_STA_0$result_STA_0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1, 
            _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1,        _1_main__store_int$left_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)168,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            _1_main__load_unsigned_int$left_STA_0$result_STA_0,        _1_main__constant_unsigned_int$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__PlusA_unsigned_int_unsigned_int2unsigned_int$right_STA_0$result_STA_0$left_STA_1,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)168,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            _1_main__store_unsigned_int$left_STA_0$right_STA_1,        _1_main__goto$label_LAB_0,        (unsigned char)171,        (unsigned char)255, 
            (unsigned char)255,        (unsigned char)255,        _1_main__goto$label_LAB_0,        (unsigned char)166, 
            (unsigned char)255,        (unsigned char)255,        (unsigned char)255,        _1_main__constant_int$result_STA_0$value_LIT_0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)172,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        _1_main__store_int$left_STA_0$right_STA_1,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)176,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            _1_main__store_int$left_STA_0$right_STA_1,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)180, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        _1_main__store_int$left_STA_0$right_STA_1, 
            _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)184,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        _1_main__store_int$left_STA_0$right_STA_1,        _1_main__string$result_STA_0$value_LIT_0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__convert_void_star2void_star$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)192,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        _1_main__store_void_star$left_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)208,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)200,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        _1_main__store_void_star$left_STA_0$right_STA_1,        _1_main__call$func_LIT_0,        (unsigned char)2, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__constant_int$result_STA_0$value_LIT_0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)212,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        _1_main__store_int$left_STA_0$right_STA_1,        _1_main__goto$label_LAB_0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)212,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            _1_main__load_int$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)208,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0,        _1_main__Lt_int_int2int$right_STA_0$result_STA_0$left_STA_1, 
            _1_main__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)14,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__goto$label_LAB_0,        (unsigned char)109, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        _1_main__string$result_STA_0$value_LIT_0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__convert_void_star2void_star$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)216,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        _1_main__store_void_star$left_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)180,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)224,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        _1_main__store_void_star$left_STA_0$right_STA_1,        _1_main__call$func_LIT_0,        (unsigned char)3, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)180,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            _1_main__load_int$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)24,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_void_star$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)184,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            _1_main__load_int$left_STA_0$result_STA_0,        _1_main__convert_int2unsigned_long$left_STA_0$result_STA_0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1, 
            _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1,        _1_main__store_int$left_STA_0$right_STA_1,        _1_main__constant_int$result_STA_0$value_LIT_0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)232,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        _1_main__store_int$left_STA_0$right_STA_1,        _1_main__goto$label_LAB_0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)232,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            _1_main__load_int$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)184,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0,        _1_main__Lt_int_int2int$right_STA_0$result_STA_0$left_STA_1, 
            _1_main__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)14,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__goto$label_LAB_0,        (unsigned char)207, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)24,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_void_star$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)232,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0,        _1_main__convert_int2unsigned_long$left_STA_0$result_STA_0, 
            _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1, 
            _1_main__load_int$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)180,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0,        _1_main__Eq_int_int2int$right_STA_0$result_STA_0$left_STA_1, 
            _1_main__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)9,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__goto$label_LAB_0,        (unsigned char)128,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)2, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)212,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            _1_main__load_int$left_STA_0$result_STA_0,        _1_main__Mod_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_main__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)9, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__goto$label_LAB_0, 
            (unsigned char)41,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)232,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)184,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            _1_main__load_int$left_STA_0$result_STA_0,        _1_main__MinusA_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusA_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)176,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            _1_main__load_int$left_STA_0$result_STA_0,        _1_main__PlusA_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)176, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        _1_main__store_int$left_STA_0$right_STA_1, 
            _1_main__goto$label_LAB_0,        (unsigned char)41,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)232, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)184,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0,        _1_main__MinusA_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusA_int_int2int$left_STA_0$result_STA_0$right_STA_1, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)172,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0,        _1_main__PlusA_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)172,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            _1_main__store_int$left_STA_0$right_STA_1,        _1_main__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)232,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            _1_main__load_int$left_STA_0$result_STA_0,        _1_main__MinusA_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)184, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        _1_main__store_int$left_STA_0$right_STA_1, 
            _1_main__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__goto$label_LAB_0,        (unsigned char)32,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)232,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            _1_main__load_int$left_STA_0$result_STA_0,        _1_main__PlusA_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)232, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        _1_main__store_int$left_STA_0$right_STA_1, 
            _1_main__goto$label_LAB_0,        (unsigned char)34,        (unsigned char)255,        (unsigned char)255, 
            (unsigned char)255,        _1_main__goto$label_LAB_0,        (unsigned char)29,        (unsigned char)255, 
            (unsigned char)255,        (unsigned char)255,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)184,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            _1_main__load_int$left_STA_0$result_STA_0,        _1_main__PlusA_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)184, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        _1_main__store_int$left_STA_0$right_STA_1, 
            _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)212,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0,        _1_main__PlusA_int_int2int$left_STA_0$result_STA_0$right_STA_1, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)212,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        _1_main__store_int$left_STA_0$right_STA_1,        _1_main__goto$label_LAB_0,        (unsigned char)132, 
            (unsigned char)254,        (unsigned char)255,        (unsigned char)255,        _1_main__goto$label_LAB_0, 
            (unsigned char)127,        (unsigned char)254,        (unsigned char)255,        (unsigned char)255, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)176,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)172, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0, 
            _1_main__Gt_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_main__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)9,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__goto$label_LAB_0,        (unsigned char)26, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__string$result_STA_0$value_LIT_0, 
            (unsigned char)3,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__convert_void_star2void_star$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)240,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        _1_main__store_void_star$left_STA_0$right_STA_1,        _1_main__call$func_LIT_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__goto$label_LAB_0,        (unsigned char)26,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__string$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__convert_void_star2void_star$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)248,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            _1_main__store_void_star$left_STA_0$right_STA_1,        _1_main__call$func_LIT_0,        (unsigned char)5,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__goto$label_LAB_0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__constant_int$result_STA_0$value_LIT_0, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)20,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0,        _1_main__PlusA_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)20,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__store_int$left_STA_0$right_STA_1,        _1_main__goto$label_LAB_0,        (unsigned char)26,        (unsigned char)253, 
            (unsigned char)255,        (unsigned char)255,        _1_main__goto$label_LAB_0,        (unsigned char)21, 
            (unsigned char)253,        (unsigned char)255,        (unsigned char)255,        _1_main__constant_int$result_STA_0$value_LIT_0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__return_int$expr_STA_0}};
extern void exit(int status ) ;
extern int puts(char const   *__s ) ;
extern int raise(int sig ) ;
extern int fprintf(struct _IO_FILE *stream , char const   *format  , ...) ;
extern int rand() ;
int myname[1000] ;
extern unsigned long strtoul(char const   *str , char const   *endptr , int base ) ;
extern int strncmp(char const   *s1 , char const   *s2 , unsigned long maxlen ) ;
int max(int a , int b ) ;
extern int printf(char const   * __restrict  __format  , ...) ;
extern int gettimeofday(struct timeval *tv , void *tz  , ...) ;
void test(void) ;
int main(void) ;
void megaInit(void) ;
extern unsigned long strlen(char const   *s ) ;
char const   *_1_main_$strings  =    "%d\000xay\n\000amr\n\000";
extern long strtol(char const   *str , char const   *endptr , int base ) ;
union _1_main_$node {
   void *_void_star ;
   unsigned long _unsigned_long ;
   unsigned int _unsigned_int ;
   int _int ;
};
extern void *memcpy(void *s1 , void const   *s2 , unsigned long size ) ;
struct timeval {
   long tv_sec ;
   long tv_usec ;
};
extern unsigned long strnlen(char const   *s , unsigned long maxlen ) ;
extern void *malloc(unsigned long size ) ;
extern int scanf(char const   * __restrict  __format  , ...)  __asm__("__isoc99_scanf")  ;
void test(void) 
{ 


  {
  printf((char const   */* __restrict  */)"Halfopen\n");
  printf((char const   */* __restrict  */)"Halfopen\n");
  printf((char const   */* __restrict  */)"Halfopen\n");
  printf((char const   */* __restrict  */)"Halfopen\n");
  printf((char const   */* __restrict  */)"Halfopen\n");
  printf((char const   */* __restrict  */)"Halfopen\n");
  printf((char const   */* __restrict  */)"Halfopen\n");
  printf((char const   */* __restrict  */)"Halfopen\n");
  return;
}
}
int max(int a , int b ) 
{ 


  {
  if (a > b) {
    return (a);
  } else {
    return (b);
  }
}
}
int main(void) 
{ 
  char _1_main_$locals[512] ;
  union _1_main_$node _1_main_$stack[1][32] ;
  union _1_main_$node *_1_main_$sp[1] ;
  unsigned char *_1_main_$pc[1] ;

  {
  megaInit();
  _1_main_$sp[0] = _1_main_$stack[0];
  _1_main_$pc[0] = _1_main_$array[0];
  while (1) {
    switch (*(_1_main_$pc[0])) {
    case _1_main__PlusA_unsigned_int_unsigned_int2unsigned_int$right_STA_0$result_STA_0$left_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_unsigned_int = (_1_main_$sp[0] + -1)->_unsigned_int + (_1_main_$sp[0] + 0)->_unsigned_int;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__store_unsigned_int$left_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    *((unsigned int *)(_1_main_$sp[0] + 0)->_void_star) = (_1_main_$sp[0] + -1)->_unsigned_int;
    _1_main_$sp[0] += -2;
    break;
    case _1_main__constant_unsigned_int$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_unsigned_int = *((unsigned int *)_1_main_$pc[0]);
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 4;
    break;
    case _1_main__Eq_int_int2int$right_STA_0$result_STA_0$left_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_int = (_1_main_$sp[0] + -1)->_int == (_1_main_$sp[0] + 0)->_int;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_unsigned_long = (_1_main_$sp[0] + -1)->_unsigned_long * (_1_main_$sp[0] + 0)->_unsigned_long;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__convert_void_star2void_star$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_void_star = (_1_main_$sp[0] + 0)->_void_star;
    break;
    case _1_main__store_void_star$left_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    *((void **)(_1_main_$sp[0] + 0)->_void_star) = (_1_main_$sp[0] + -1)->_void_star;
    _1_main_$sp[0] += -2;
    break;
    case _1_main__store_int$left_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    *((int *)(_1_main_$sp[0] + 0)->_void_star) = (_1_main_$sp[0] + -1)->_int;
    _1_main_$sp[0] += -2;
    break;
    case _1_main__string$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_void_star = (void *)(_1_main_$strings + *((int *)_1_main_$pc[0]));
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 4;
    break;
    case _1_main__Gt_int_int2int$left_STA_0$result_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_int = (_1_main_$sp[0] + 0)->_int > (_1_main_$sp[0] + -1)->_int;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__label$label_LAB_0: 
    (_1_main_$pc[0]) ++;
    break;
    case _1_main__goto$label_LAB_0: 
    (_1_main_$pc[0]) ++;
    _1_main_$pc[0] += *((int *)_1_main_$pc[0]);
    break;
    case _1_main__MinusA_int_int2int$left_STA_0$result_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_int = (_1_main_$sp[0] + 0)->_int - (_1_main_$sp[0] + -1)->_int;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__convert_int2unsigned_long$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_unsigned_long = (unsigned long )(_1_main_$sp[0] + 0)->_int;
    break;
    case _1_main__local$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_void_star = (void *)(_1_main_$locals + *((int *)_1_main_$pc[0]));
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 4;
    break;
    case _1_main__Lt_int_int2int$right_STA_0$result_STA_0$left_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_int = (_1_main_$sp[0] + -1)->_int < (_1_main_$sp[0] + 0)->_int;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__branchIfTrue$expr_STA_0$label_LAB_0: 
    (_1_main_$pc[0]) ++;
    if ((_1_main_$sp[0] + 0)->_int) {
      _1_main_$pc[0] += *((int *)_1_main_$pc[0]);
    } else {
      _1_main_$pc[0] += 4;
    }
    (_1_main_$sp[0]) --;
    break;
    case _1_main__load_unsigned_int$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_unsigned_int = *((unsigned int *)(_1_main_$sp[0] + 0)->_void_star);
    break;
    case _1_main__constant_void_star$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_void_star = *((void **)_1_main_$pc[0]);
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 8;
    break;
    case _1_main__return_int$expr_STA_0: 
    (_1_main_$pc[0]) ++;
    return ((_1_main_$sp[0] + 0)->_int);
    break;
    case _1_main__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_void_star = (_1_main_$sp[0] + -1)->_void_star + (_1_main_$sp[0] + 0)->_int;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__constant_unsigned_long$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_unsigned_long = *((unsigned long *)_1_main_$pc[0]);
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 8;
    break;
    case _1_main__Ge_unsigned_int_unsigned_int2int$right_STA_0$result_STA_0$left_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_int = (_1_main_$sp[0] + -1)->_unsigned_int >= (_1_main_$sp[0] + 0)->_unsigned_int;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__load_int$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_int = *((int *)(_1_main_$sp[0] + 0)->_void_star);
    break;
    case _1_main__call$func_LIT_0: 
    (_1_main_$pc[0]) ++;
    switch (*((int *)_1_main_$pc[0])) {
    case 4: 
    printf(*((char const   * __restrict  *)(_1_main_$locals + 496)));
    break;
    case 3: 
    scanf(*((char const   * __restrict  *)(_1_main_$locals + 472)), *((int **)(_1_main_$locals + 480)));
    break;
    case 1: 
    scanf(*((char const   * __restrict  *)(_1_main_$locals + 0)), *((int **)(_1_main_$locals + 8)));
    break;
    case 2: 
    scanf(*((char const   * __restrict  *)(_1_main_$locals + 448)), *((int **)(_1_main_$locals + 456)));
    break;
    case 5: 
    printf(*((char const   * __restrict  *)(_1_main_$locals + 504)));
    break;
    }
    _1_main_$pc[0] += 4;
    break;
    case _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_void_star = (_1_main_$sp[0] + 0)->_void_star + (_1_main_$sp[0] + -1)->_unsigned_long;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__Mod_int_int2int$left_STA_0$result_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_int = (_1_main_$sp[0] + 0)->_int % (_1_main_$sp[0] + -1)->_int;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__convert_unsigned_int2unsigned_long$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_unsigned_long = (unsigned long )(_1_main_$sp[0] + 0)->_unsigned_int;
    break;
    case _1_main__constant_int$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_int = *((int *)_1_main_$pc[0]);
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 4;
    break;
    case _1_main__PlusA_int_int2int$left_STA_0$result_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_int = (_1_main_$sp[0] + 0)->_int + (_1_main_$sp[0] + -1)->_int;
    (_1_main_$sp[0]) --;
    break;
    }
  }
}
}
int havefun(void) 
{ 


  {
  puts("have fun");
  return (0);
}
}
void megaInit(void) 
{ 


  {
  myname_i$nit();
}
}
void myname_i$nit(void) 
{ 


  {
  myname[0] = 0;
}
}
