/* Generated by CIL v. 1.7.0 */
/* print_CIL_Input is false */

union _1_main_$node;
struct _IO_FILE;
enum _1_main_$op;
struct timeval;
extern float strtof(char const   *str , char const   *endptr ) ;
extern void signal(int sig , void *func ) ;
typedef unsigned long size_t;
typedef struct _IO_FILE FILE;
extern double strtod(char const   *str , char const   *endptr ) ;
extern int fclose(void *stream ) ;
extern void *fopen(char const   *filename , char const   *mode ) ;
extern void abort() ;
enum _1_main_$op {
    _1_main__return_int$expr_STA_0 = 34,
    _1_main__MinusA_int_int2int$left_STA_0$result_STA_0$right_STA_1 = 175,
    _1_main__load_char$left_STA_0$result_STA_0 = 15,
    _1_main__Gt_int_int2int$right_STA_0$result_STA_0$left_STA_1 = 214,
    _1_main__store_int$left_STA_0$right_STA_1 = 58,
    _1_main__branchIfTrue$expr_STA_0$label_LAB_0 = 22,
    _1_main__constant_unsigned_long$result_STA_0$value_LIT_0 = 89,
    _1_main__constant_char$result_STA_0$value_LIT_0 = 241,
    _1_main__store_unsigned_long$right_STA_0$left_STA_1 = 124,
    _1_main__constant_void_star$result_STA_0$value_LIT_0 = 233,
    _1_main__label$label_LAB_0 = 85,
    _1_main__string$result_STA_0$value_LIT_0 = 137,
    _1_main__load_unsigned_long$left_STA_0$result_STA_0 = 240,
    _1_main__local$result_STA_0$value_LIT_0 = 31,
    _1_main__convert_void_star2void_star$left_STA_0$result_STA_0 = 166,
    _1_main__constant_int$result_STA_0$value_LIT_0 = 7,
    _1_main__goto$label_LAB_0 = 55,
    _1_main__Lt_int_int2int$right_STA_0$result_STA_0$left_STA_1 = 105,
    _1_main__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1 = 94,
    _1_main__Ge_int_int2int$left_STA_0$result_STA_0$right_STA_1 = 33,
    _1_main__store_void_star$right_STA_0$left_STA_1 = 191,
    _1_main__convert_int2unsigned_long$left_STA_0$result_STA_0 = 60,
    _1_main__Le_int_int2int$right_STA_0$result_STA_0$left_STA_1 = 8,
    _1_main__store_char$right_STA_0$left_STA_1 = 254,
    _1_main__load_int$left_STA_0$result_STA_0 = 239,
    _1_main__convert_int2char$left_STA_0$result_STA_0 = 108,
    _1_main__PlusA_int_int2int$left_STA_0$result_STA_0$right_STA_1 = 252,
    _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1 = 125,
    _1_main__convert_unsigned_long2int$left_STA_0$result_STA_0 = 212,
    _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1 = 150,
    _1_main__convert_char2int$left_STA_0$result_STA_0 = 132,
    _1_main__call$func_LIT_0 = 235
} ;
unsigned char _1_main_$array[1][1031]  = { {        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__string$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__store_void_star$right_STA_0$left_STA_1,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)8,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)16,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__store_void_star$right_STA_0$left_STA_1,        _1_main__call$func_LIT_0,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__constant_int$result_STA_0$value_LIT_0, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)20,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__store_int$left_STA_0$right_STA_1,        _1_main__goto$label_LAB_0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)20,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__load_int$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)16,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0,        _1_main__Le_int_int2int$right_STA_0$result_STA_0$left_STA_1, 
            _1_main__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)14,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__goto$label_LAB_0,        (unsigned char)190, 
            (unsigned char)3,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)24,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__string$result_STA_0$value_LIT_0,        (unsigned char)3,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__store_void_star$right_STA_0$left_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)32, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__constant_void_star$result_STA_0$value_LIT_0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)40,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__store_void_star$right_STA_0$left_STA_1,        _1_main__call$func_LIT_0, 
            (unsigned char)2,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)18,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        _1_main__string$result_STA_0$value_LIT_0,        (unsigned char)3,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__store_void_star$right_STA_0$left_STA_1,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)28,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_void_star$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1, 
            _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)36,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        _1_main__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__store_void_star$right_STA_0$left_STA_1, 
            _1_main__call$func_LIT_0,        (unsigned char)3,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)18,        (unsigned char)8, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_void_star$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)40,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__convert_void_star2void_star$left_STA_0$result_STA_0,        _1_main__store_void_star$right_STA_0$left_STA_1,        _1_main__call$func_LIT_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)28,        (unsigned char)8,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)40,        (unsigned char)8, 
            (unsigned char)0,        (unsigned char)0,        _1_main__load_unsigned_long$left_STA_0$result_STA_0,        _1_main__store_unsigned_long$right_STA_0$left_STA_1, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)28,        (unsigned char)8,        (unsigned char)0, 
            (unsigned char)0,        _1_main__load_unsigned_long$left_STA_0$result_STA_0,        _1_main__convert_unsigned_long2int$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)48,        (unsigned char)8,        (unsigned char)0,        (unsigned char)0, 
            _1_main__store_int$left_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)56,        (unsigned char)8, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_void_star$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)36,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0, 
            _1_main__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__convert_void_star2void_star$left_STA_0$result_STA_0,        _1_main__store_void_star$right_STA_0$left_STA_1,        _1_main__call$func_LIT_0, 
            (unsigned char)5,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)64,        (unsigned char)8,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)72,        (unsigned char)8, 
            (unsigned char)0,        (unsigned char)0,        _1_main__load_unsigned_long$left_STA_0$result_STA_0,        _1_main__store_unsigned_long$right_STA_0$left_STA_1, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)64,        (unsigned char)8,        (unsigned char)0, 
            (unsigned char)0,        _1_main__load_unsigned_long$left_STA_0$result_STA_0,        _1_main__convert_unsigned_long2int$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)80,        (unsigned char)8,        (unsigned char)0,        (unsigned char)0, 
            _1_main__store_int$left_STA_0$right_STA_1,        _1_main__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)48, 
            (unsigned char)8,        (unsigned char)0,        (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)80,        (unsigned char)8,        (unsigned char)0, 
            (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0,        _1_main__Lt_int_int2int$right_STA_0$result_STA_0$left_STA_1,        _1_main__branchIfTrue$expr_STA_0$label_LAB_0, 
            (unsigned char)9,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__goto$label_LAB_0,        (unsigned char)21,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)80,        (unsigned char)8, 
            (unsigned char)0,        (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)84,        (unsigned char)8,        (unsigned char)0,        (unsigned char)0, 
            _1_main__store_int$left_STA_0$right_STA_1,        _1_main__goto$label_LAB_0,        (unsigned char)21,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)48, 
            (unsigned char)8,        (unsigned char)0,        (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)84,        (unsigned char)8,        (unsigned char)0, 
            (unsigned char)0,        _1_main__store_int$left_STA_0$right_STA_1,        _1_main__goto$label_LAB_0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__constant_int$result_STA_0$value_LIT_0, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)48,        (unsigned char)8,        (unsigned char)0, 
            (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0,        _1_main__MinusA_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)48,        (unsigned char)8,        (unsigned char)0,        (unsigned char)0, 
            _1_main__store_int$left_STA_0$right_STA_1,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)80, 
            (unsigned char)8,        (unsigned char)0,        (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0, 
            _1_main__MinusA_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)80,        (unsigned char)8, 
            (unsigned char)0,        (unsigned char)0,        _1_main__store_int$left_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)88,        (unsigned char)8,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_char$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__store_char$right_STA_0$left_STA_1,        _1_main__constant_void_star$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)84,        (unsigned char)8,        (unsigned char)0,        (unsigned char)0, 
            _1_main__load_int$left_STA_0$result_STA_0,        _1_main__convert_int2unsigned_long$left_STA_0$result_STA_0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1, 
            _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)89,        (unsigned char)8, 
            (unsigned char)0,        (unsigned char)0,        _1_main__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)88,        (unsigned char)8,        (unsigned char)0,        (unsigned char)0, 
            _1_main__load_char$left_STA_0$result_STA_0,        _1_main__store_char$right_STA_0$left_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)88, 
            (unsigned char)8,        (unsigned char)0,        (unsigned char)0,        _1_main__load_char$left_STA_0$result_STA_0, 
            _1_main__convert_char2int$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)44,        (unsigned char)16, 
            (unsigned char)0,        (unsigned char)0,        _1_main__store_int$left_STA_0$right_STA_1,        _1_main__constant_int$result_STA_0$value_LIT_0, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)84,        (unsigned char)8,        (unsigned char)0, 
            (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0,        _1_main__MinusA_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)48,        (unsigned char)16,        (unsigned char)0,        (unsigned char)0, 
            _1_main__store_int$left_STA_0$right_STA_1,        _1_main__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)48,        (unsigned char)16,        (unsigned char)0,        (unsigned char)0, 
            _1_main__load_int$left_STA_0$result_STA_0,        _1_main__Ge_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_main__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)14, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__goto$label_LAB_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__goto$label_LAB_0,        (unsigned char)110,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)44,        (unsigned char)16, 
            (unsigned char)0,        (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)52,        (unsigned char)16,        (unsigned char)0,        (unsigned char)0, 
            _1_main__store_int$left_STA_0$right_STA_1,        _1_main__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)48,        (unsigned char)8,        (unsigned char)0,        (unsigned char)0, 
            _1_main__load_int$left_STA_0$result_STA_0,        _1_main__Ge_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_main__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)9, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__goto$label_LAB_0, 
            (unsigned char)63,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)48,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__constant_void_star$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)48, 
            (unsigned char)8,        (unsigned char)0,        (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0, 
            _1_main__convert_int2unsigned_long$left_STA_0$result_STA_0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)40,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__load_char$left_STA_0$result_STA_0,        _1_main__convert_char2int$left_STA_0$result_STA_0, 
            _1_main__MinusA_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)52,        (unsigned char)16, 
            (unsigned char)0,        (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0,        _1_main__PlusA_int_int2int$left_STA_0$result_STA_0$right_STA_1, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)52,        (unsigned char)16,        (unsigned char)0, 
            (unsigned char)0,        _1_main__store_int$left_STA_0$right_STA_1,        _1_main__goto$label_LAB_0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__constant_int$result_STA_0$value_LIT_0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)80,        (unsigned char)8,        (unsigned char)0, 
            (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0,        _1_main__Ge_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_main__branchIfTrue$expr_STA_0$label_LAB_0, 
            (unsigned char)9,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__goto$label_LAB_0,        (unsigned char)63,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)48,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_void_star$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)80,        (unsigned char)8,        (unsigned char)0,        (unsigned char)0, 
            _1_main__load_int$left_STA_0$result_STA_0,        _1_main__convert_int2unsigned_long$left_STA_0$result_STA_0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1, 
            _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)36,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        _1_main__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__load_char$left_STA_0$result_STA_0, 
            _1_main__convert_char2int$left_STA_0$result_STA_0,        _1_main__MinusA_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)52, 
            (unsigned char)16,        (unsigned char)0,        (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0, 
            _1_main__PlusA_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)52,        (unsigned char)16, 
            (unsigned char)0,        (unsigned char)0,        _1_main__store_int$left_STA_0$right_STA_1,        _1_main__goto$label_LAB_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)52,        (unsigned char)16,        (unsigned char)0, 
            (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)9, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__Gt_int_int2int$right_STA_0$result_STA_0$left_STA_1, 
            _1_main__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)9,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__goto$label_LAB_0,        (unsigned char)38,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)10, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)52,        (unsigned char)16,        (unsigned char)0,        (unsigned char)0, 
            _1_main__load_int$left_STA_0$result_STA_0,        _1_main__MinusA_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)52, 
            (unsigned char)16,        (unsigned char)0,        (unsigned char)0,        _1_main__store_int$left_STA_0$right_STA_1, 
            _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)44,        (unsigned char)16, 
            (unsigned char)0,        (unsigned char)0,        _1_main__store_int$left_STA_0$right_STA_1,        _1_main__goto$label_LAB_0, 
            (unsigned char)20,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)44,        (unsigned char)16, 
            (unsigned char)0,        (unsigned char)0,        _1_main__store_int$left_STA_0$right_STA_1,        _1_main__goto$label_LAB_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_void_star$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)48,        (unsigned char)16, 
            (unsigned char)0,        (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0,        _1_main__convert_int2unsigned_long$left_STA_0$result_STA_0, 
            _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)89,        (unsigned char)8,        (unsigned char)0,        (unsigned char)0, 
            _1_main__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)48,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)52, 
            (unsigned char)16,        (unsigned char)0,        (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0, 
            _1_main__PlusA_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_main__convert_int2char$left_STA_0$result_STA_0,        _1_main__store_char$right_STA_0$left_STA_1,        _1_main__constant_int$result_STA_0$value_LIT_0, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)48,        (unsigned char)8,        (unsigned char)0, 
            (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0,        _1_main__MinusA_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)48,        (unsigned char)8,        (unsigned char)0,        (unsigned char)0, 
            _1_main__store_int$left_STA_0$right_STA_1,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)80, 
            (unsigned char)8,        (unsigned char)0,        (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0, 
            _1_main__MinusA_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)80,        (unsigned char)8, 
            (unsigned char)0,        (unsigned char)0,        _1_main__store_int$left_STA_0$right_STA_1,        _1_main__constant_int$result_STA_0$value_LIT_0, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)48,        (unsigned char)16,        (unsigned char)0, 
            (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0,        _1_main__MinusA_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)48,        (unsigned char)16,        (unsigned char)0,        (unsigned char)0, 
            _1_main__store_int$left_STA_0$right_STA_1,        _1_main__goto$label_LAB_0,        (unsigned char)132,        (unsigned char)254, 
            (unsigned char)255,        (unsigned char)255,        _1_main__goto$label_LAB_0,        (unsigned char)127, 
            (unsigned char)254,        (unsigned char)255,        (unsigned char)255,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)44,        (unsigned char)16,        (unsigned char)0,        (unsigned char)0, 
            _1_main__load_int$left_STA_0$result_STA_0,        _1_main__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)9,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__goto$label_LAB_0,        (unsigned char)25, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__constant_int$result_STA_0$value_LIT_0, 
            (unsigned char)49,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)56,        (unsigned char)16,        (unsigned char)0, 
            (unsigned char)0,        _1_main__store_int$left_STA_0$right_STA_1,        _1_main__call$func_LIT_0,        (unsigned char)6, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__goto$label_LAB_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)64,        (unsigned char)16,        (unsigned char)0, 
            (unsigned char)0,        _1_main__string$result_STA_0$value_LIT_0,        (unsigned char)6,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__store_void_star$right_STA_0$left_STA_1,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)72,        (unsigned char)16,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_void_star$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1, 
            _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)89,        (unsigned char)8, 
            (unsigned char)0,        (unsigned char)0,        _1_main__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__store_void_star$right_STA_0$left_STA_1, 
            _1_main__call$func_LIT_0,        (unsigned char)7,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)20, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0, 
            _1_main__PlusA_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)20,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__store_int$left_STA_0$right_STA_1,        _1_main__goto$label_LAB_0, 
            (unsigned char)51,        (unsigned char)252,        (unsigned char)255,        (unsigned char)255, 
            _1_main__goto$label_LAB_0,        (unsigned char)46,        (unsigned char)252,        (unsigned char)255, 
            (unsigned char)255,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__return_int$expr_STA_0}};
extern void exit(int status ) ;
extern int raise(int sig ) ;
extern int fprintf(struct _IO_FILE *stream , char const   *format  , ...) ;
extern unsigned long strtoul(char const   *str , char const   *endptr , int base ) ;
extern int rand() ;
extern int strncmp(char const   *s1 , char const   *s2 , unsigned long maxlen ) ;
extern int ( /* missing proto */  printf)() ;
extern int gettimeofday(struct timeval *tv , void *tz  , ...) ;
int main(void) ;
void megaInit(void) ;
extern  __attribute__((__nothrow__)) size_t ( __attribute__((__nonnull__(1), __leaf__)) strlen)(char const   *__s )  __attribute__((__pure__)) ;
char const   *_1_main_$strings  =    "%d\000%s\000%s\n\000";
extern int ( /* missing proto */  putchar)() ;
extern long strtol(char const   *str , char const   *endptr , int base ) ;
union _1_main_$node {
   void *_void_star ;
   unsigned long _unsigned_long ;
   int _int ;
   char _char ;
};
extern void *memcpy(void *s1 , void const   *s2 , unsigned long size ) ;
struct timeval {
   long tv_sec ;
   long tv_usec ;
};
extern unsigned long strnlen(char const   *s , unsigned long maxlen ) ;
extern void *malloc(unsigned long size ) ;
extern int ( /* missing proto */  scanf)() ;
int main(void) 
{ 
  char _1_main_$locals[4176] ;
  union _1_main_$node _1_main_$stack[1][32] ;
  union _1_main_$node *_1_main_$sp[1] ;
  unsigned char *_1_main_$pc[1] ;

  {
  megaInit();
  _1_main_$sp[0] = _1_main_$stack[0];
  _1_main_$pc[0] = _1_main_$array[0];
  while (1) {
    switch (*(_1_main_$pc[0])) {
    case _1_main__load_char$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_char = *((char *)(_1_main_$sp[0] + 0)->_void_star);
    break;
    case _1_main__Lt_int_int2int$right_STA_0$result_STA_0$left_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_int = (_1_main_$sp[0] + -1)->_int < (_1_main_$sp[0] + 0)->_int;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__load_int$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_int = *((int *)(_1_main_$sp[0] + 0)->_void_star);
    break;
    case _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_void_star = (_1_main_$sp[0] + 0)->_void_star + (_1_main_$sp[0] + -1)->_unsigned_long;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__PlusA_int_int2int$left_STA_0$result_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_int = (_1_main_$sp[0] + 0)->_int + (_1_main_$sp[0] + -1)->_int;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__convert_void_star2void_star$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_void_star = (_1_main_$sp[0] + 0)->_void_star;
    break;
    case _1_main__convert_unsigned_long2int$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_int = (int )(_1_main_$sp[0] + 0)->_unsigned_long;
    break;
    case _1_main__constant_void_star$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_void_star = *((void **)_1_main_$pc[0]);
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 8;
    break;
    case _1_main__store_void_star$right_STA_0$left_STA_1: 
    (_1_main_$pc[0]) ++;
    *((void **)(_1_main_$sp[0] + -1)->_void_star) = (_1_main_$sp[0] + 0)->_void_star;
    _1_main_$sp[0] += -2;
    break;
    case _1_main__local$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_void_star = (void *)(_1_main_$locals + *((int *)_1_main_$pc[0]));
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 4;
    break;
    case _1_main__convert_int2char$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_char = (char )(_1_main_$sp[0] + 0)->_int;
    break;
    case _1_main__Gt_int_int2int$right_STA_0$result_STA_0$left_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_int = (_1_main_$sp[0] + -1)->_int > (_1_main_$sp[0] + 0)->_int;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__constant_unsigned_long$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_unsigned_long = *((unsigned long *)_1_main_$pc[0]);
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 8;
    break;
    case _1_main__goto$label_LAB_0: 
    (_1_main_$pc[0]) ++;
    _1_main_$pc[0] += *((int *)_1_main_$pc[0]);
    break;
    case _1_main__string$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_void_star = (void *)(_1_main_$strings + *((int *)_1_main_$pc[0]));
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 4;
    break;
    case _1_main__MinusA_int_int2int$left_STA_0$result_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_int = (_1_main_$sp[0] + 0)->_int - (_1_main_$sp[0] + -1)->_int;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__label$label_LAB_0: 
    (_1_main_$pc[0]) ++;
    break;
    case _1_main__load_unsigned_long$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_unsigned_long = *((unsigned long *)(_1_main_$sp[0] + 0)->_void_star);
    break;
    case _1_main__Le_int_int2int$right_STA_0$result_STA_0$left_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_int = (_1_main_$sp[0] + -1)->_int <= (_1_main_$sp[0] + 0)->_int;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__convert_char2int$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_int = (int )(_1_main_$sp[0] + 0)->_char;
    break;
    case _1_main__store_int$left_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    *((int *)(_1_main_$sp[0] + 0)->_void_star) = (_1_main_$sp[0] + -1)->_int;
    _1_main_$sp[0] += -2;
    break;
    case _1_main__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_void_star = (_1_main_$sp[0] + 0)->_void_star + (_1_main_$sp[0] + -1)->_int;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__store_unsigned_long$right_STA_0$left_STA_1: 
    (_1_main_$pc[0]) ++;
    *((unsigned long *)(_1_main_$sp[0] + -1)->_void_star) = (_1_main_$sp[0] + 0)->_unsigned_long;
    _1_main_$sp[0] += -2;
    break;
    case _1_main__return_int$expr_STA_0: 
    (_1_main_$pc[0]) ++;
    return ((_1_main_$sp[0] + 0)->_int);
    break;
    case _1_main__store_char$right_STA_0$left_STA_1: 
    (_1_main_$pc[0]) ++;
    *((char *)(_1_main_$sp[0] + -1)->_void_star) = (_1_main_$sp[0] + 0)->_char;
    _1_main_$sp[0] += -2;
    break;
    case _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_unsigned_long = (_1_main_$sp[0] + -1)->_unsigned_long * (_1_main_$sp[0] + 0)->_unsigned_long;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__Ge_int_int2int$left_STA_0$result_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_int = (_1_main_$sp[0] + 0)->_int >= (_1_main_$sp[0] + -1)->_int;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__branchIfTrue$expr_STA_0$label_LAB_0: 
    (_1_main_$pc[0]) ++;
    if ((_1_main_$sp[0] + 0)->_int) {
      _1_main_$pc[0] += *((int *)_1_main_$pc[0]);
    } else {
      _1_main_$pc[0] += 4;
    }
    (_1_main_$sp[0]) --;
    break;
    case _1_main__call$func_LIT_0: 
    (_1_main_$pc[0]) ++;
    switch (*((int *)_1_main_$pc[0])) {
    case 2: 
    scanf(*((char const   **)(_1_main_$locals + 24)), *((char **)(_1_main_$locals + 32)));
    break;
    case 3: 
    scanf(*((char const   **)(_1_main_$locals + 1042)), *((char **)(_1_main_$locals + 1052)));
    break;
    case 1: 
    scanf(*((char const   **)(_1_main_$locals + 0)), *((int **)(_1_main_$locals + 8)));
    break;
    case 6: 
    putchar(*((int *)(_1_main_$locals + 4152)));
    break;
    case 5: 
    *((unsigned long *)(_1_main_$locals + 2120)) = strlen(*((char const   **)(_1_main_$locals + 2104)));
    break;
    case 7: 
    printf(*((char const   **)(_1_main_$locals + 4160)), *((char **)(_1_main_$locals + 4168)));
    break;
    case 4: 
    *((unsigned long *)(_1_main_$locals + 2088)) = strlen(*((char const   **)(_1_main_$locals + 2066)));
    break;
    }
    _1_main_$pc[0] += 4;
    break;
    case _1_main__constant_int$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_int = *((int *)_1_main_$pc[0]);
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 4;
    break;
    case _1_main__convert_int2unsigned_long$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_unsigned_long = (unsigned long )(_1_main_$sp[0] + 0)->_int;
    break;
    case _1_main__constant_char$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_char = *((char *)_1_main_$pc[0]);
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 4;
    break;
    }
  }
}
}
void megaInit(void) 
{ 


  {

}
}
