/* Generated by CIL v. 1.7.0 */
/* print_CIL_Input is false */

union _1_main_$node;
struct _IO_FILE;
struct timeval;
enum _1_main_$op;
extern float strtof(char const   *str , char const   *endptr ) ;
extern void signal(int sig , void *func ) ;
typedef struct _IO_FILE FILE;
extern double strtod(char const   *str , char const   *endptr ) ;
extern int fclose(void *stream ) ;
extern void *fopen(char const   *filename , char const   *mode ) ;
extern void abort() ;
enum _1_main_$op {
    _1_main__branchIfTrue$expr_STA_0$label_LAB_0 = 125,
    _1_main__label$label_LAB_0 = 85,
    _1_main__call$func_LIT_0 = 235,
    _1_main__string$result_STA_0$value_LIT_0 = 150,
    _1_main__constant_int$result_STA_0$value_LIT_0 = 7,
    _1_main__Lt_int_int2int$left_STA_0$result_STA_0$right_STA_1 = 233,
    _1_main__local$result_STA_0$value_LIT_0 = 31,
    _1_main__goto$label_LAB_0 = 55,
    _1_main__PlusA_int_int2int$left_STA_0$result_STA_0$right_STA_1 = 252,
    _1_main__return_int$expr_STA_0 = 34,
    _1_main__load_int$left_STA_0$result_STA_0 = 239,
    _1_main__store_int$left_STA_0$right_STA_1 = 58,
    _1_main__Le_int_int2int$left_STA_0$result_STA_0$right_STA_1 = 89,
    _1_main__store_void_star$right_STA_0$left_STA_1 = 191,
    _1_main__convert_void_star2void_star$left_STA_0$result_STA_0 = 94
} ;
unsigned char _1_main_$array[1][328]  = { {        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__store_int$left_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)8,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__string$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__convert_void_star2void_star$left_STA_0$result_STA_0,        _1_main__store_void_star$right_STA_0$left_STA_1,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)16,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__store_void_star$right_STA_0$left_STA_1,        _1_main__call$func_LIT_0,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__constant_int$result_STA_0$value_LIT_0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)24,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__store_int$left_STA_0$right_STA_1,        _1_main__goto$label_LAB_0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__load_int$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)24,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0,        _1_main__Lt_int_int2int$left_STA_0$result_STA_0$right_STA_1, 
            _1_main__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)14,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__goto$label_LAB_0,        (unsigned char)243, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__constant_int$result_STA_0$value_LIT_0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)28,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__store_int$left_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)32, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__string$result_STA_0$value_LIT_0, 
            (unsigned char)3,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__convert_void_star2void_star$left_STA_0$result_STA_0,        _1_main__store_void_star$right_STA_0$left_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)40, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)48,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__store_void_star$right_STA_0$left_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)56,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)64, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__store_void_star$right_STA_0$left_STA_1, 
            _1_main__call$func_LIT_0,        (unsigned char)2,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)68, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__store_int$left_STA_0$right_STA_1, 
            _1_main__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)48,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)68,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__load_int$left_STA_0$result_STA_0,        _1_main__Le_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_main__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)14, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__goto$label_LAB_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__goto$label_LAB_0,        (unsigned char)92,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)68,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)72,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__store_int$left_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)64,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)76,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__store_int$left_STA_0$right_STA_1,        _1_main__call$func_LIT_0,        (unsigned char)3,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)84, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)80,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__store_int$left_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)80, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)28,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0,        _1_main__PlusA_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)28,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__store_int$left_STA_0$right_STA_1,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)68, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0, 
            _1_main__PlusA_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)68,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__store_int$left_STA_0$right_STA_1,        _1_main__goto$label_LAB_0, 
            (unsigned char)149,        (unsigned char)255,        (unsigned char)255,        (unsigned char)255, 
            _1_main__goto$label_LAB_0,        (unsigned char)144,        (unsigned char)255,        (unsigned char)255, 
            (unsigned char)255,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)88,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__string$result_STA_0$value_LIT_0,        (unsigned char)8, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__convert_void_star2void_star$left_STA_0$result_STA_0, 
            _1_main__store_void_star$right_STA_0$left_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)28,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)96,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__store_int$left_STA_0$right_STA_1,        _1_main__call$func_LIT_0,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)24,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__load_int$left_STA_0$result_STA_0,        _1_main__PlusA_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)24, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__store_int$left_STA_0$right_STA_1, 
            _1_main__goto$label_LAB_0,        (unsigned char)254,        (unsigned char)254,        (unsigned char)255, 
            (unsigned char)255,        _1_main__goto$label_LAB_0,        (unsigned char)249,        (unsigned char)254, 
            (unsigned char)255,        (unsigned char)255,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__return_int$expr_STA_0}};
extern void exit(int status ) ;
extern int raise(int sig ) ;
extern int fprintf(struct _IO_FILE *stream , char const   *format  , ...) ;
extern int rand() ;
extern unsigned long strtoul(char const   *str , char const   *endptr , int base ) ;
extern int strncmp(char const   *s1 , char const   *s2 , unsigned long maxlen ) ;
int max(int x , int y ) ;
extern int gettimeofday(struct timeval *tv , void *tz  , ...) ;
extern int printf(char const   * __restrict  __format  , ...) ;
void test(void) ;
int main(void) ;
extern unsigned long strlen(char const   *s ) ;
char const   *_1_main_$strings  =    "%d\000%d%d\000%d\n\000";
void megaInit(void) ;
extern long strtol(char const   *str , char const   *endptr , int base ) ;
int solve(int n , int r ) ;
union _1_main_$node {
   void *_void_star ;
   int _int ;
};
extern unsigned long strnlen(char const   *s , unsigned long maxlen ) ;
extern void *memcpy(void *s1 , void const   *s2 , unsigned long size ) ;
struct timeval {
   long tv_sec ;
   long tv_usec ;
};
extern void *malloc(unsigned long size ) ;
extern int scanf(char const   * __restrict  __format  , ...)  __asm__("__isoc99_scanf")  ;
int solve(int n , int r ) 
{ 
  int primer[5133] ;
  unsigned int tmp ;
  int size ;
  int i ;
  int tmp___0 ;
  int tmp___1 ;
  int sum ;
  int msk ;
  int mult ;
  int bits ;
  int i___0 ;
  int cur ;

  {
  primer[0] = 0;
  tmp = 1U;
  while (! (tmp >= 5133U)) {
    primer[tmp] = 0;
    tmp ++;
  }
  size = 0;
  i = 2;
  while (i * i <= n) {
    if (n % i == 0) {
      tmp___0 = size;
      size ++;
      primer[tmp___0] = i;
      while (n % i == 0) {
        n /= i;
      }
    }
    i ++;
  }
  if (n > 1) {
    tmp___1 = size;
    size ++;
    primer[tmp___1] = n;
  }
  sum = 0;
  msk = 1;
  while (msk < 1 << size) {
    mult = 1;
    bits = 0;
    i___0 = 0;
    while (i___0 < size) {
      if (msk & (1 << i___0)) {
        bits ++;
        mult *= primer[i___0];
      }
      i___0 ++;
    }
    cur = r / mult;
    if (bits % 2 == 1) {
      sum += cur;
    } else {
      sum -= cur;
    }
    msk ++;
  }
  return (r - sum);
}
}
void megaInit(void) 
{ 


  {

}
}
int max(int x , int y ) 
{ 
  int z ;

  {
  z = 0;
  if (x > y) {
    z = x;
  } else {
    x = y;
  }
  return (z);
}
}
void test(void) 
{ 


  {
  printf((char const   */* __restrict  */)"Halfopen\n");
  printf((char const   */* __restrict  */)"Halfopen\n");
  printf((char const   */* __restrict  */)"Halfopen\n");
  printf((char const   */* __restrict  */)"Halfopen\n");
  printf((char const   */* __restrict  */)"Halfopen\n");
  printf((char const   */* __restrict  */)"Halfopen\n");
  printf((char const   */* __restrict  */)"Halfopen\n");
  printf((char const   */* __restrict  */)"Halfopen\n");
  return;
}
}
int main(void) 
{ 
  char _1_main_$locals[100] ;
  union _1_main_$node _1_main_$stack[1][32] ;
  union _1_main_$node *_1_main_$sp[1] ;
  unsigned char *_1_main_$pc[1] ;

  {
  megaInit();
  _1_main_$sp[0] = _1_main_$stack[0];
  _1_main_$pc[0] = _1_main_$array[0];
  while (1) {
    switch (*(_1_main_$pc[0])) {
    case _1_main__Le_int_int2int$left_STA_0$result_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_int = (_1_main_$sp[0] + 0)->_int <= (_1_main_$sp[0] + -1)->_int;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__string$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_void_star = (void *)(_1_main_$strings + *((int *)_1_main_$pc[0]));
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 4;
    break;
    case _1_main__label$label_LAB_0: 
    (_1_main_$pc[0]) ++;
    break;
    case _1_main__load_int$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_int = *((int *)(_1_main_$sp[0] + 0)->_void_star);
    break;
    case _1_main__store_void_star$right_STA_0$left_STA_1: 
    (_1_main_$pc[0]) ++;
    *((void **)(_1_main_$sp[0] + -1)->_void_star) = (_1_main_$sp[0] + 0)->_void_star;
    _1_main_$sp[0] += -2;
    break;
    case _1_main__branchIfTrue$expr_STA_0$label_LAB_0: 
    (_1_main_$pc[0]) ++;
    if ((_1_main_$sp[0] + 0)->_int) {
      _1_main_$pc[0] += *((int *)_1_main_$pc[0]);
    } else {
      _1_main_$pc[0] += 4;
    }
    (_1_main_$sp[0]) --;
    break;
    case _1_main__convert_void_star2void_star$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_void_star = (_1_main_$sp[0] + 0)->_void_star;
    break;
    case _1_main__store_int$left_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    *((int *)(_1_main_$sp[0] + 0)->_void_star) = (_1_main_$sp[0] + -1)->_int;
    _1_main_$sp[0] += -2;
    break;
    case _1_main__local$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_void_star = (void *)(_1_main_$locals + *((int *)_1_main_$pc[0]));
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 4;
    break;
    case _1_main__Lt_int_int2int$left_STA_0$result_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_int = (_1_main_$sp[0] + 0)->_int < (_1_main_$sp[0] + -1)->_int;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__PlusA_int_int2int$left_STA_0$result_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_int = (_1_main_$sp[0] + 0)->_int + (_1_main_$sp[0] + -1)->_int;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__return_int$expr_STA_0: 
    (_1_main_$pc[0]) ++;
    return ((_1_main_$sp[0] + 0)->_int);
    break;
    case _1_main__goto$label_LAB_0: 
    (_1_main_$pc[0]) ++;
    _1_main_$pc[0] += *((int *)_1_main_$pc[0]);
    break;
    case _1_main__call$func_LIT_0: 
    (_1_main_$pc[0]) ++;
    switch (*((int *)_1_main_$pc[0])) {
    case 1: 
    scanf(*((char const   * __restrict  *)(_1_main_$locals + 8)), *((int **)(_1_main_$locals + 16)));
    break;
    case 4: 
    printf(*((char const   * __restrict  *)(_1_main_$locals + 88)), *((int *)(_1_main_$locals + 96)));
    break;
    case 3: 
    *((int *)(_1_main_$locals + 84)) = solve(*((int *)(_1_main_$locals + 72)), *((int *)(_1_main_$locals + 76)));
    break;
    case 2: 
    scanf(*((char const   * __restrict  *)(_1_main_$locals + 32)), *((int **)(_1_main_$locals + 40)),
          *((int **)(_1_main_$locals + 56)));
    break;
    }
    _1_main_$pc[0] += 4;
    break;
    case _1_main__constant_int$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_int = *((int *)_1_main_$pc[0]);
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 4;
    break;
    }
  }
}
}
