/* Generated by CIL v. 1.7.0 */
/* print_CIL_Input is false */

struct _IO_FILE;
enum _1_main_$op;
union _1_main_$node;
struct timeval;
double e ;
extern  __attribute__((__nothrow__)) double ( __attribute__((__leaf__)) sqrt)(double __x ) ;
double d ;
extern float strtof(char const   *str , char const   *endptr ) ;
extern void signal(int sig , void *func ) ;
typedef struct _IO_FILE FILE;
double H ;
extern double strtod(char const   *str , char const   *endptr ) ;
extern int fclose(void *stream ) ;
extern void *fopen(char const   *filename , char const   *mode ) ;
void H_i$nit(void) ;
extern void abort() ;
enum _1_main_$op {
    _1_main__Div_double_double2double$right_STA_0$result_STA_0$left_STA_1 = 254,
    _1_main__MinusA_double_double2double$right_STA_0$result_STA_0$left_STA_1 = 60,
    _1_main__return_int$expr_STA_0 = 34,
    _1_main__load_double$left_STA_0$result_STA_0 = 89,
    _1_main__string$result_STA_0$value_LIT_0 = 94,
    _1_main__goto$label_LAB_0 = 55,
    _1_main__convert_int2double$left_STA_0$result_STA_0 = 108,
    _1_main__store_int$right_STA_0$left_STA_1 = 31,
    _1_main__constant_double$result_STA_0$value_LIT_0 = 22,
    _1_main__convert_double2int$left_STA_0$result_STA_0 = 150,
    _1_main__label$label_LAB_0 = 85,
    _1_main__store_void_star$left_STA_0$right_STA_1 = 235,
    _1_main__local$result_STA_0$value_LIT_0 = 252,
    _1_main__load_int$left_STA_0$result_STA_0 = 239,
    _1_main__global$result_STA_0$value_LIT_0 = 233,
    _1_main__Gt_double_double2int$right_STA_0$result_STA_0$left_STA_1 = 132,
    _1_main__call$func_LIT_0 = 58,
    _1_main__convert_void_star2void_star$left_STA_0$result_STA_0 = 191,
    _1_main__branchIfTrue$expr_STA_0$label_LAB_0 = 214,
    _1_main__store_double$left_STA_0$right_STA_1 = 175,
    _1_main__constant_int$result_STA_0$value_LIT_0 = 7,
    _1_main__PlusA_double_double2double$left_STA_0$result_STA_0$right_STA_1 = 125,
    _1_main__Mult_double_double2double$left_STA_0$result_STA_0$right_STA_1 = 137
} ;
unsigned char _1_main_$array[1][568]  = { {        _1_main__string$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__convert_void_star2void_star$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__store_void_star$left_STA_0$right_STA_1, 
            _1_main__global$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__store_void_star$left_STA_0$right_STA_1,        _1_main__global$result_STA_0$value_LIT_0, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)16,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__store_void_star$left_STA_0$right_STA_1,        _1_main__call$func_LIT_0,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__goto$label_LAB_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__string$result_STA_0$value_LIT_0,        (unsigned char)7,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__convert_void_star2void_star$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)24, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__store_void_star$left_STA_0$right_STA_1, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)40,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)32,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__store_void_star$left_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)56,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)48,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__store_void_star$left_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)72, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)64,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__store_void_star$left_STA_0$right_STA_1,        _1_main__call$func_LIT_0,        (unsigned char)2,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__goto$label_LAB_0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)40,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__load_double$left_STA_0$result_STA_0,        _1_main__global$result_STA_0$value_LIT_0,        (unsigned char)2,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__load_double$left_STA_0$result_STA_0,        _1_main__Gt_double_double2int$right_STA_0$result_STA_0$left_STA_1, 
            _1_main__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)9,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__goto$label_LAB_0,        (unsigned char)98,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)56, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__load_double$left_STA_0$result_STA_0, 
            _1_main__global$result_STA_0$value_LIT_0,        (unsigned char)2,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__load_double$left_STA_0$result_STA_0,        _1_main__Gt_double_double2int$right_STA_0$result_STA_0$left_STA_1,        _1_main__branchIfTrue$expr_STA_0$label_LAB_0, 
            (unsigned char)9,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__goto$label_LAB_0,        (unsigned char)59,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)72,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__load_double$left_STA_0$result_STA_0,        _1_main__global$result_STA_0$value_LIT_0, 
            (unsigned char)2,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__load_double$left_STA_0$result_STA_0,        _1_main__Gt_double_double2int$right_STA_0$result_STA_0$left_STA_1,        _1_main__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)9, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__goto$label_LAB_0, 
            (unsigned char)20,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)80,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__store_int$right_STA_0$left_STA_1,        _1_main__goto$label_LAB_0, 
            (unsigned char)52,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)80,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__store_int$right_STA_0$left_STA_1,        _1_main__goto$label_LAB_0, 
            (unsigned char)36,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)80,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__store_int$right_STA_0$left_STA_1,        _1_main__goto$label_LAB_0, 
            (unsigned char)20,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)80,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__store_int$right_STA_0$left_STA_1,        _1_main__goto$label_LAB_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)80,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0,        _1_main__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)14, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__goto$label_LAB_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__goto$label_LAB_0,        (unsigned char)57,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        _1_main__constant_double$result_STA_0$value_LIT_0,        (unsigned char)56,        (unsigned char)233, 
            (unsigned char)47,        (unsigned char)84,        (unsigned char)251,        (unsigned char)33, 
            (unsigned char)9,        (unsigned char)64,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)40, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__load_double$left_STA_0$result_STA_0, 
            _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)180,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__convert_int2double$left_STA_0$result_STA_0,        _1_main__Div_double_double2double$right_STA_0$result_STA_0$left_STA_1,        _1_main__Mult_double_double2double$left_STA_0$result_STA_0$right_STA_1, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)88,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__store_double$left_STA_0$right_STA_1,        _1_main__call$func_LIT_0,        (unsigned char)3, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)96,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__load_double$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)40,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__store_double$left_STA_0$right_STA_1,        _1_main__constant_double$result_STA_0$value_LIT_0, 
            (unsigned char)56,        (unsigned char)233,        (unsigned char)47,        (unsigned char)84, 
            (unsigned char)251,        (unsigned char)33,        (unsigned char)9,        (unsigned char)64, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)56,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__load_double$left_STA_0$result_STA_0,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)180, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__convert_int2double$left_STA_0$result_STA_0, 
            _1_main__Div_double_double2double$right_STA_0$result_STA_0$left_STA_1,        _1_main__Mult_double_double2double$left_STA_0$result_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)104, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__store_double$left_STA_0$right_STA_1, 
            _1_main__call$func_LIT_0,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)112,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__load_double$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)56,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__store_double$left_STA_0$right_STA_1,        _1_main__constant_double$result_STA_0$value_LIT_0,        (unsigned char)56,        (unsigned char)233, 
            (unsigned char)47,        (unsigned char)84,        (unsigned char)251,        (unsigned char)33, 
            (unsigned char)9,        (unsigned char)64,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)72, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__load_double$left_STA_0$result_STA_0, 
            _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)180,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__convert_int2double$left_STA_0$result_STA_0,        _1_main__Div_double_double2double$right_STA_0$result_STA_0$left_STA_1,        _1_main__Mult_double_double2double$left_STA_0$result_STA_0$right_STA_1, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)120,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__store_double$left_STA_0$right_STA_1,        _1_main__call$func_LIT_0,        (unsigned char)5, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)128,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__load_double$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)72,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__store_double$left_STA_0$right_STA_1,        _1_main__constant_double$result_STA_0$value_LIT_0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)64, 
            _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__convert_int2double$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)72, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__load_double$left_STA_0$result_STA_0, 
            _1_main__Div_double_double2double$right_STA_0$result_STA_0$left_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)72,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__load_double$left_STA_0$result_STA_0,        _1_main__Div_double_double2double$right_STA_0$result_STA_0$left_STA_1, 
            _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__convert_int2double$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)40, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__load_double$left_STA_0$result_STA_0, 
            _1_main__Div_double_double2double$right_STA_0$result_STA_0$left_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)40,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__load_double$left_STA_0$result_STA_0,        _1_main__Div_double_double2double$right_STA_0$result_STA_0$left_STA_1, 
            _1_main__PlusA_double_double2double$left_STA_0$result_STA_0$right_STA_1,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)2,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__convert_int2double$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)56,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__load_double$left_STA_0$result_STA_0,        _1_main__Div_double_double2double$right_STA_0$result_STA_0$left_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)56, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__load_double$left_STA_0$result_STA_0, 
            _1_main__Div_double_double2double$right_STA_0$result_STA_0$left_STA_1,        _1_main__MinusA_double_double2double$right_STA_0$result_STA_0$left_STA_1,        _1_main__Div_double_double2double$right_STA_0$result_STA_0$left_STA_1,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)136,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__store_double$left_STA_0$right_STA_1,        _1_main__call$func_LIT_0,        (unsigned char)6,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)152, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__load_double$left_STA_0$result_STA_0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)144,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__store_double$left_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)160, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__constant_double$result_STA_0$value_LIT_0, 
            (unsigned char)143,        (unsigned char)56,        (unsigned char)67,        (unsigned char)245, 
            (unsigned char)255,        (unsigned char)255,        (unsigned char)223,        (unsigned char)63, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)144,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__load_double$left_STA_0$result_STA_0,        _1_main__global$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__load_double$left_STA_0$result_STA_0, 
            _1_main__Mult_double_double2double$left_STA_0$result_STA_0$right_STA_1,        _1_main__global$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__load_double$left_STA_0$result_STA_0,        _1_main__PlusA_double_double2double$left_STA_0$result_STA_0$right_STA_1, 
            _1_main__PlusA_double_double2double$left_STA_0$result_STA_0$right_STA_1,        _1_main__convert_double2int$left_STA_0$result_STA_0,        _1_main__store_int$right_STA_0$left_STA_1,        _1_main__string$result_STA_0$value_LIT_0, 
            (unsigned char)17,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__convert_void_star2void_star$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)168,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__store_void_star$left_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)176,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)160,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0,        _1_main__store_int$right_STA_0$left_STA_1,        _1_main__call$func_LIT_0, 
            (unsigned char)7,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__goto$label_LAB_0,        (unsigned char)3,        (unsigned char)254,        (unsigned char)255, 
            (unsigned char)255,        _1_main__goto$label_LAB_0,        (unsigned char)254,        (unsigned char)253, 
            (unsigned char)255,        (unsigned char)255,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__return_int$expr_STA_0}};
extern void exit(int status ) ;
extern  __attribute__((__nothrow__)) double ( __attribute__((__leaf__)) tan)(double __x ) ;
extern int raise(int sig ) ;
extern int fprintf(struct _IO_FILE *stream , char const   *format  , ...) ;
extern unsigned long strtoul(char const   *str , char const   *endptr , int base ) ;
extern int rand() ;
extern int strncmp(char const   *s1 , char const   *s2 , unsigned long maxlen ) ;
extern int printf(char const   * __restrict  __format  , ...) ;
extern int gettimeofday(struct timeval *tv , void *tz  , ...) ;
int main(void) ;
extern unsigned long strlen(char const   *s ) ;
char const   *_1_main_$strings  =    "%lf%lf\000%lf%lf%lf\000%d\n\000";
void megaInit(void) ;
void e_i$nit(void) ;
void d_i$nit(void) ;
extern long strtol(char const   *str , char const   *endptr , int base ) ;
union _1_main_$node {
   double _double ;
   void *_void_star ;
   int _int ;
};
extern unsigned long strnlen(char const   *s , unsigned long maxlen ) ;
struct timeval {
   long tv_sec ;
   long tv_usec ;
};
extern void *memcpy(void *s1 , void const   *s2 , unsigned long size ) ;
extern void *malloc(unsigned long size ) ;
extern int scanf(char const   * __restrict  __format  , ...)  __asm__("__isoc99_scanf")  ;
void d_i$nit(void) 
{ 


  {
  d = 0.;
}
}
int main(void) 
{ 
  char _1_main_$locals[180] ;
  union _1_main_$node _1_main_$stack[1][32] ;
  union _1_main_$node *_1_main_$sp[1] ;
  unsigned char *_1_main_$pc[1] ;

  {
  megaInit();
  _1_main_$sp[0] = _1_main_$stack[0];
  _1_main_$pc[0] = _1_main_$array[0];
  while (1) {
    switch (*(_1_main_$pc[0])) {
    case _1_main__store_double$left_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    *((double *)(_1_main_$sp[0] + 0)->_void_star) = (_1_main_$sp[0] + -1)->_double;
    _1_main_$sp[0] += -2;
    break;
    case _1_main__branchIfTrue$expr_STA_0$label_LAB_0: 
    (_1_main_$pc[0]) ++;
    if ((_1_main_$sp[0] + 0)->_int) {
      _1_main_$pc[0] += *((int *)_1_main_$pc[0]);
    } else {
      _1_main_$pc[0] += 4;
    }
    (_1_main_$sp[0]) --;
    break;
    case _1_main__convert_int2double$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_double = (double )(_1_main_$sp[0] + 0)->_int;
    break;
    case _1_main__MinusA_double_double2double$right_STA_0$result_STA_0$left_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_double = (_1_main_$sp[0] + -1)->_double - (_1_main_$sp[0] + 0)->_double;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__load_int$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_int = *((int *)(_1_main_$sp[0] + 0)->_void_star);
    break;
    case _1_main__global$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    switch (*((int *)_1_main_$pc[0])) {
    case 2: 
    (_1_main_$sp[0] + 1)->_void_star = (void *)(& e);
    break;
    case 0: 
    (_1_main_$sp[0] + 1)->_void_star = (void *)(& d);
    break;
    case 1: 
    (_1_main_$sp[0] + 1)->_void_star = (void *)(& H);
    break;
    }
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 4;
    break;
    case _1_main__string$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_void_star = (void *)(_1_main_$strings + *((int *)_1_main_$pc[0]));
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 4;
    break;
    case _1_main__goto$label_LAB_0: 
    (_1_main_$pc[0]) ++;
    _1_main_$pc[0] += *((int *)_1_main_$pc[0]);
    break;
    case _1_main__load_double$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_double = *((double *)(_1_main_$sp[0] + 0)->_void_star);
    break;
    case _1_main__store_void_star$left_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    *((void **)(_1_main_$sp[0] + 0)->_void_star) = (_1_main_$sp[0] + -1)->_void_star;
    _1_main_$sp[0] += -2;
    break;
    case _1_main__store_int$right_STA_0$left_STA_1: 
    (_1_main_$pc[0]) ++;
    *((int *)(_1_main_$sp[0] + -1)->_void_star) = (_1_main_$sp[0] + 0)->_int;
    _1_main_$sp[0] += -2;
    break;
    case _1_main__constant_double$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_double = *((double *)_1_main_$pc[0]);
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 8;
    break;
    case _1_main__return_int$expr_STA_0: 
    (_1_main_$pc[0]) ++;
    return ((_1_main_$sp[0] + 0)->_int);
    break;
    case _1_main__PlusA_double_double2double$left_STA_0$result_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_double = (_1_main_$sp[0] + 0)->_double + (_1_main_$sp[0] + -1)->_double;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__Gt_double_double2int$right_STA_0$result_STA_0$left_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_int = (_1_main_$sp[0] + -1)->_double > (_1_main_$sp[0] + 0)->_double;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__call$func_LIT_0: 
    (_1_main_$pc[0]) ++;
    switch (*((int *)_1_main_$pc[0])) {
    case 4: 
    *((double *)(_1_main_$locals + 112)) = tan(*((double *)(_1_main_$locals + 104)));
    break;
    case 6: 
    *((double *)(_1_main_$locals + 152)) = sqrt(*((double *)(_1_main_$locals + 136)));
    break;
    case 3: 
    *((double *)(_1_main_$locals + 96)) = tan(*((double *)(_1_main_$locals + 88)));
    break;
    case 7: 
    printf(*((char const   * __restrict  *)(_1_main_$locals + 168)), *((int *)(_1_main_$locals + 176)));
    break;
    case 5: 
    *((double *)(_1_main_$locals + 128)) = tan(*((double *)(_1_main_$locals + 120)));
    break;
    case 2: 
    scanf(*((char const   * __restrict  *)(_1_main_$locals + 24)), *((double **)(_1_main_$locals + 32)),
          *((double **)(_1_main_$locals + 48)), *((double **)(_1_main_$locals + 64)));
    break;
    case 1: 
    scanf(*((char const   * __restrict  *)(_1_main_$locals + 0)), *((double **)(_1_main_$locals + 8)),
          *((double **)(_1_main_$locals + 16)));
    break;
    }
    _1_main_$pc[0] += 4;
    break;
    case _1_main__local$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_void_star = (void *)(_1_main_$locals + *((int *)_1_main_$pc[0]));
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 4;
    break;
    case _1_main__label$label_LAB_0: 
    (_1_main_$pc[0]) ++;
    break;
    case _1_main__convert_void_star2void_star$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_void_star = (_1_main_$sp[0] + 0)->_void_star;
    break;
    case _1_main__Div_double_double2double$right_STA_0$result_STA_0$left_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_double = (_1_main_$sp[0] + -1)->_double / (_1_main_$sp[0] + 0)->_double;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__convert_double2int$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_int = (int )(_1_main_$sp[0] + 0)->_double;
    break;
    case _1_main__Mult_double_double2double$left_STA_0$result_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_double = (_1_main_$sp[0] + 0)->_double * (_1_main_$sp[0] + -1)->_double;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__constant_int$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_int = *((int *)_1_main_$pc[0]);
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 4;
    break;
    }
  }
}
}
void H_i$nit(void) 
{ 


  {
  H = 0.;
}
}
void megaInit(void) 
{ 


  {
  d_i$nit();
  e_i$nit();
  H_i$nit();
}
}
void e_i$nit(void) 
{ 


  {
  e = 0.00000001;
}
}
