/* Generated by CIL v. 1.7.0 */
/* print_CIL_Input is false */

enum _1_main_$op;
union _1_main_$node;
struct _IO_FILE;
struct timeval;
extern void signal(int sig , void *func ) ;
extern float strtof(char const   *str , char const   *endptr ) ;
typedef struct _IO_FILE FILE;
extern double strtod(char const   *str , char const   *endptr ) ;
extern int fclose(void *stream ) ;
extern void *fopen(char const   *filename , char const   *mode ) ;
extern void abort() ;
enum _1_main_$op {
    _1_main__Ne_int_int2int$right_STA_0$result_STA_0$left_STA_1 = 241,
    _1_main__convert_void_star2void_star$left_STA_0$result_STA_0 = 239,
    _1_main__store_void_star$right_STA_0$left_STA_1 = 31,
    _1_main__Mult_double_double2double$left_STA_0$result_STA_0$right_STA_1 = 214,
    _1_main__load_int$left_STA_0$result_STA_0 = 105,
    _1_main__constant_unsigned_long$result_STA_0$value_LIT_0 = 60,
    _1_main__convert_char2unsigned_long$left_STA_0$result_STA_0 = 15,
    _1_main__Lt_double_double2int$left_STA_0$result_STA_0$right_STA_1 = 150,
    _1_main__constant_void_star$result_STA_0$value_LIT_0 = 108,
    _1_main__MinusA_double_double2double$left_STA_0$result_STA_0$right_STA_1 = 137,
    _1_main__label$label_LAB_0 = 85,
    _1_main__load_void_star$left_STA_0$result_STA_0 = 235,
    _1_main__local$result_STA_0$value_LIT_0 = 252,
    _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1 = 254,
    _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1 = 175,
    _1_main__branchIfTrue$expr_STA_0$label_LAB_0 = 94,
    _1_main__convert_int2double$left_STA_0$result_STA_0 = 132,
    _1_main__load_double$left_STA_0$result_STA_0 = 125,
    _1_main__constant_int$result_STA_0$value_LIT_0 = 7,
    _1_main__constant_double$result_STA_0$value_LIT_0 = 89,
    _1_main__convert_int2unsigned_long$left_STA_0$result_STA_0 = 240,
    _1_main__goto$label_LAB_0 = 55,
    _1_main__load_char$left_STA_0$result_STA_0 = 33,
    _1_main__string$result_STA_0$value_LIT_0 = 191,
    _1_main__call$func_LIT_0 = 58,
    _1_main__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1 = 22,
    _1_main__store_double$right_STA_0$left_STA_1 = 233,
    _1_main__store_int$left_STA_0$right_STA_1 = 212,
    _1_main__return_int$expr_STA_0 = 34
} ;
unsigned char _1_main_$array[1][1250]  = { {        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__constant_void_star$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)8, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__constant_int$result_STA_0$value_LIT_0, 
            (unsigned char)116,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__convert_int2unsigned_long$left_STA_0$result_STA_0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1, 
            _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)100,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__convert_int2double$left_STA_0$result_STA_0,        _1_main__store_double$right_STA_0$left_STA_1,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_void_star$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)110, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__convert_int2unsigned_long$left_STA_0$result_STA_0, 
            _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1,        _1_main__constant_int$result_STA_0$value_LIT_0, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__convert_int2double$left_STA_0$result_STA_0,        _1_main__store_double$right_STA_0$left_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__constant_void_star$result_STA_0$value_LIT_0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)99,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__convert_int2unsigned_long$left_STA_0$result_STA_0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1, 
            _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1,        _1_main__constant_double$result_STA_0$value_LIT_0,        (unsigned char)82, 
            (unsigned char)184,        (unsigned char)30,        (unsigned char)133,        (unsigned char)235, 
            (unsigned char)81,        (unsigned char)4,        (unsigned char)64,        _1_main__store_double$right_STA_0$left_STA_1, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__constant_void_star$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)8, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__constant_int$result_STA_0$value_LIT_0, 
            (unsigned char)98,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__convert_int2unsigned_long$left_STA_0$result_STA_0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1, 
            _1_main__constant_double$result_STA_0$value_LIT_0,        (unsigned char)92,        (unsigned char)143,        (unsigned char)194, 
            (unsigned char)245,        (unsigned char)40,        (unsigned char)220,        (unsigned char)70, 
            (unsigned char)64,        _1_main__store_double$right_STA_0$left_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__constant_void_star$result_STA_0$value_LIT_0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)101,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__convert_int2unsigned_long$left_STA_0$result_STA_0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1, 
            _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1,        _1_main__constant_double$result_STA_0$value_LIT_0,        (unsigned char)123, 
            (unsigned char)20,        (unsigned char)174,        (unsigned char)71,        (unsigned char)225, 
            (unsigned char)122,        (unsigned char)62,        (unsigned char)64,        _1_main__store_double$right_STA_0$left_STA_1, 
            _1_main__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        _1_main__string$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__convert_void_star2void_star$left_STA_0$result_STA_0, 
            _1_main__store_void_star$right_STA_0$left_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)16, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        _1_main__constant_void_star$result_STA_0$value_LIT_0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1, 
            _1_main__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1,        _1_main__store_void_star$right_STA_0$left_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)40, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)48,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_void_star$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1, 
            _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)12,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1, 
            _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1,        _1_main__store_void_star$right_STA_0$left_STA_1,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)88,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)16,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        _1_main__constant_void_star$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)8, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1,        _1_main__store_void_star$right_STA_0$left_STA_1, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)96,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)48,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_void_star$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0, 
            (unsigned char)12,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1, 
            _1_main__store_void_star$right_STA_0$left_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)104,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)16, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        _1_main__constant_void_star$result_STA_0$value_LIT_0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)2,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1, 
            _1_main__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1,        _1_main__store_void_star$right_STA_0$left_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)112, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)48,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_void_star$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1, 
            _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)12,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)2, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1, 
            _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1,        _1_main__store_void_star$right_STA_0$left_STA_1,        _1_main__call$func_LIT_0, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)124,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)120, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        _1_main__store_int$left_STA_0$right_STA_1, 
            _1_main__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)120,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        _1_main__load_int$left_STA_0$result_STA_0,        _1_main__constant_int$result_STA_0$value_LIT_0, 
            (unsigned char)255,        (unsigned char)255,        (unsigned char)255,        (unsigned char)255, 
            _1_main__Ne_int_int2int$right_STA_0$result_STA_0$left_STA_1,        _1_main__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)14,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__goto$label_LAB_0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__goto$label_LAB_0, 
            (unsigned char)160,        (unsigned char)2,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)16,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        _1_main__constant_void_star$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)8, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_void_star$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)48, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        _1_main__constant_void_star$result_STA_0$value_LIT_0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)2,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1, 
            _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)12,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1, 
            _1_main__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1,        _1_main__load_char$left_STA_0$result_STA_0,        _1_main__convert_char2unsigned_long$left_STA_0$result_STA_0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1, 
            _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1,        _1_main__load_double$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)16,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_void_star$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1, 
            _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1,        _1_main__load_double$left_STA_0$result_STA_0,        _1_main__Mult_double_double2double$left_STA_0$result_STA_0$right_STA_1, 
            _1_main__store_double$right_STA_0$left_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)16,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_void_star$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0, 
            (unsigned char)8,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__constant_void_star$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)8, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)48,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_void_star$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)2, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1, 
            _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)12,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1, 
            _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1,        _1_main__load_char$left_STA_0$result_STA_0,        _1_main__convert_char2unsigned_long$left_STA_0$result_STA_0, 
            _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1,        _1_main__load_double$left_STA_0$result_STA_0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)16,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        _1_main__constant_void_star$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)8, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1,        _1_main__load_double$left_STA_0$result_STA_0, 
            _1_main__Mult_double_double2double$left_STA_0$result_STA_0$right_STA_1,        _1_main__store_double$right_STA_0$left_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)128, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        _1_main__constant_int$result_STA_0$value_LIT_0, 
            (unsigned char)6,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__convert_int2double$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)16,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_void_star$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0, 
            (unsigned char)8,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1, 
            _1_main__load_double$left_STA_0$result_STA_0,        _1_main__Mult_double_double2double$left_STA_0$result_STA_0$right_STA_1,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)16, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        _1_main__constant_void_star$result_STA_0$value_LIT_0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1, 
            _1_main__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1,        _1_main__load_double$left_STA_0$result_STA_0,        _1_main__MinusA_double_double2double$left_STA_0$result_STA_0$right_STA_1,        _1_main__store_double$right_STA_0$left_STA_1, 
            _1_main__call$func_LIT_0,        (unsigned char)2,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)136,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)144, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        _1_main__load_double$left_STA_0$result_STA_0, 
            _1_main__store_double$right_STA_0$left_STA_1,        _1_main__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_double$result_STA_0$value_LIT_0,        (unsigned char)149, 
            (unsigned char)214,        (unsigned char)38,        (unsigned char)232,        (unsigned char)11, 
            (unsigned char)46,        (unsigned char)17,        (unsigned char)62,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)136,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0, 
            _1_main__load_double$left_STA_0$result_STA_0,        _1_main__Lt_double_double2int$left_STA_0$result_STA_0$right_STA_1,        _1_main__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)9, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__goto$label_LAB_0, 
            (unsigned char)20,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)152,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        _1_main__string$result_STA_0$value_LIT_0,        (unsigned char)23,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__store_void_star$right_STA_0$left_STA_1,        _1_main__goto$label_LAB_0, 
            (unsigned char)180,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)160,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)16,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_void_star$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0, 
            (unsigned char)8,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1, 
            _1_main__load_double$left_STA_0$result_STA_0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)16,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        _1_main__constant_void_star$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__constant_unsigned_long$result_STA_0$value_LIT_0, 
            (unsigned char)8,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _1_main__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1, 
            _1_main__load_double$left_STA_0$result_STA_0,        _1_main__MinusA_double_double2double$left_STA_0$result_STA_0$right_STA_1,        _1_main__store_double$right_STA_0$left_STA_1,        _1_main__call$func_LIT_0, 
            (unsigned char)3,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)168,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)176,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        _1_main__load_double$left_STA_0$result_STA_0,        _1_main__store_double$right_STA_0$left_STA_1, 
            _1_main__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__constant_double$result_STA_0$value_LIT_0,        (unsigned char)149,        (unsigned char)214, 
            (unsigned char)38,        (unsigned char)232,        (unsigned char)11,        (unsigned char)46, 
            (unsigned char)17,        (unsigned char)62,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)168, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        _1_main__load_double$left_STA_0$result_STA_0, 
            _1_main__Lt_double_double2int$left_STA_0$result_STA_0$right_STA_1,        _1_main__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)9,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__goto$label_LAB_0,        (unsigned char)20, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)184,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0, 
            _1_main__string$result_STA_0$value_LIT_0,        (unsigned char)35,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__store_void_star$right_STA_0$left_STA_1,        _1_main__goto$label_LAB_0,        (unsigned char)20, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)184,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0, 
            _1_main__string$result_STA_0$value_LIT_0,        (unsigned char)42,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__store_void_star$right_STA_0$left_STA_1,        _1_main__goto$label_LAB_0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0, 
            (unsigned char)152,        (unsigned char)4,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)184,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        _1_main__load_void_star$left_STA_0$result_STA_0,        _1_main__store_void_star$right_STA_0$left_STA_1,        _1_main__goto$label_LAB_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)192,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        _1_main__local$result_STA_0$value_LIT_0,        (unsigned char)152,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        _1_main__load_void_star$left_STA_0$result_STA_0,        _1_main__convert_void_star2void_star$left_STA_0$result_STA_0, 
            _1_main__store_void_star$right_STA_0$left_STA_1,        _1_main__call$func_LIT_0,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_main__goto$label_LAB_0,        (unsigned char)254, 
            (unsigned char)251,        (unsigned char)255,        (unsigned char)255,        _1_main__goto$label_LAB_0, 
            (unsigned char)249,        (unsigned char)251,        (unsigned char)255,        (unsigned char)255, 
            _1_main__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_main__return_int$expr_STA_0}};
extern void exit(int status ) ;
extern int raise(int sig ) ;
extern int fprintf(struct _IO_FILE *stream , char const   *format  , ...) ;
extern int rand() ;
extern unsigned long strtoul(char const   *str , char const   *endptr , int base ) ;
extern int strncmp(char const   *s1 , char const   *s2 , unsigned long maxlen ) ;
extern int gettimeofday(struct timeval *tv , void *tz  , ...) ;
extern int printf(char const   * __restrict  __format  , ...) ;
extern  __attribute__((__nothrow__)) double ( __attribute__((__leaf__)) fabs)(double __x )  __attribute__((__const__)) ;
int main(void) ;
extern unsigned long strlen(char const   *s ) ;
char const   *_1_main_$strings  =    "%lf %s\n%lf %s\n%lf %s\n\n\000Excellent\n\n\000Spin\n\n\000Neither\n\n\000";
void megaInit(void) ;
extern long strtol(char const   *str , char const   *endptr , int base ) ;
union _1_main_$node {
   double _double ;
   void *_void_star ;
   unsigned long _unsigned_long ;
   int _int ;
   char _char ;
};
extern unsigned long strnlen(char const   *s , unsigned long maxlen ) ;
extern void *memcpy(void *s1 , void const   *s2 , unsigned long size ) ;
struct timeval {
   long tv_sec ;
   long tv_usec ;
};
extern void *malloc(unsigned long size ) ;
extern int scanf(char const   * __restrict  __format  , ...)  __asm__("__isoc99_scanf")  ;
int main(void) 
{ 
  char _1_main_$locals[1224] ;
  union _1_main_$node _1_main_$stack[1][32] ;
  union _1_main_$node *_1_main_$sp[1] ;
  unsigned char *_1_main_$pc[1] ;

  {
  megaInit();
  _1_main_$sp[0] = _1_main_$stack[0];
  _1_main_$pc[0] = _1_main_$array[0];
  while (1) {
    switch (*(_1_main_$pc[0])) {
    case _1_main__convert_int2unsigned_long$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_unsigned_long = (unsigned long )(_1_main_$sp[0] + 0)->_int;
    break;
    case _1_main__load_int$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_int = *((int *)(_1_main_$sp[0] + 0)->_void_star);
    break;
    case _1_main__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_void_star = (_1_main_$sp[0] + 0)->_void_star + (_1_main_$sp[0] + -1)->_unsigned_long;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__convert_int2double$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_double = (double )(_1_main_$sp[0] + 0)->_int;
    break;
    case _1_main__convert_void_star2void_star$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_void_star = (_1_main_$sp[0] + 0)->_void_star;
    break;
    case _1_main__convert_char2unsigned_long$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_unsigned_long = (unsigned long )(_1_main_$sp[0] + 0)->_char;
    break;
    case _1_main__return_int$expr_STA_0: 
    (_1_main_$pc[0]) ++;
    return ((_1_main_$sp[0] + 0)->_int);
    break;
    case _1_main__MinusA_double_double2double$left_STA_0$result_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_double = (_1_main_$sp[0] + 0)->_double - (_1_main_$sp[0] + -1)->_double;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__load_double$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_double = *((double *)(_1_main_$sp[0] + 0)->_void_star);
    break;
    case _1_main__constant_void_star$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_void_star = *((void **)_1_main_$pc[0]);
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 8;
    break;
    case _1_main__Mult_double_double2double$left_STA_0$result_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_double = (_1_main_$sp[0] + 0)->_double * (_1_main_$sp[0] + -1)->_double;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_void_star = (_1_main_$sp[0] + -1)->_void_star + (_1_main_$sp[0] + 0)->_int;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__local$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_void_star = (void *)(_1_main_$locals + *((int *)_1_main_$pc[0]));
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 4;
    break;
    case _1_main__load_char$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_char = *((char *)(_1_main_$sp[0] + 0)->_void_star);
    break;
    case _1_main__store_double$right_STA_0$left_STA_1: 
    (_1_main_$pc[0]) ++;
    *((double *)(_1_main_$sp[0] + -1)->_void_star) = (_1_main_$sp[0] + 0)->_double;
    _1_main_$sp[0] += -2;
    break;
    case _1_main__store_int$left_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    *((int *)(_1_main_$sp[0] + 0)->_void_star) = (_1_main_$sp[0] + -1)->_int;
    _1_main_$sp[0] += -2;
    break;
    case _1_main__constant_double$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_double = *((double *)_1_main_$pc[0]);
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 8;
    break;
    case _1_main__constant_unsigned_long$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_unsigned_long = *((unsigned long *)_1_main_$pc[0]);
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 8;
    break;
    case _1_main__Lt_double_double2int$left_STA_0$result_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_int = (_1_main_$sp[0] + 0)->_double < (_1_main_$sp[0] + -1)->_double;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__constant_int$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_int = *((int *)_1_main_$pc[0]);
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 4;
    break;
    case _1_main__label$label_LAB_0: 
    (_1_main_$pc[0]) ++;
    break;
    case _1_main__load_void_star$left_STA_0$result_STA_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 0)->_void_star = *((void **)(_1_main_$sp[0] + 0)->_void_star);
    break;
    case _1_main__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_unsigned_long = (_1_main_$sp[0] + 0)->_unsigned_long * (_1_main_$sp[0] + -1)->_unsigned_long;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__goto$label_LAB_0: 
    (_1_main_$pc[0]) ++;
    _1_main_$pc[0] += *((int *)_1_main_$pc[0]);
    break;
    case _1_main__call$func_LIT_0: 
    (_1_main_$pc[0]) ++;
    switch (*((int *)_1_main_$pc[0])) {
    case 1: 
    *((int *)(_1_main_$locals + 1148)) = scanf(*((char const   * __restrict  *)(_1_main_$locals + 1024)),
                                               *((double **)(_1_main_$locals + 1032)),
                                               *((char **)(_1_main_$locals + 1064)),
                                               *((double **)(_1_main_$locals + 1112)),
                                               *((char **)(_1_main_$locals + 1120)),
                                               *((double **)(_1_main_$locals + 1128)),
                                               *((char **)(_1_main_$locals + 1136)));
    break;
    case 3: 
    *((double *)(_1_main_$locals + 1200)) = fabs(*((double *)(_1_main_$locals + 1184)));
    break;
    case 4: 
    printf(*((char const   * __restrict  *)(_1_main_$locals + 1216)));
    break;
    case 2: 
    *((double *)(_1_main_$locals + 1168)) = fabs(*((double *)(_1_main_$locals + 1152)));
    break;
    }
    _1_main_$pc[0] += 4;
    break;
    case _1_main__store_void_star$right_STA_0$left_STA_1: 
    (_1_main_$pc[0]) ++;
    *((void **)(_1_main_$sp[0] + -1)->_void_star) = (_1_main_$sp[0] + 0)->_void_star;
    _1_main_$sp[0] += -2;
    break;
    case _1_main__Ne_int_int2int$right_STA_0$result_STA_0$left_STA_1: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + -1)->_int = (_1_main_$sp[0] + -1)->_int != (_1_main_$sp[0] + 0)->_int;
    (_1_main_$sp[0]) --;
    break;
    case _1_main__string$result_STA_0$value_LIT_0: 
    (_1_main_$pc[0]) ++;
    (_1_main_$sp[0] + 1)->_void_star = (void *)(_1_main_$strings + *((int *)_1_main_$pc[0]));
    (_1_main_$sp[0]) ++;
    _1_main_$pc[0] += 4;
    break;
    case _1_main__branchIfTrue$expr_STA_0$label_LAB_0: 
    (_1_main_$pc[0]) ++;
    if ((_1_main_$sp[0] + 0)->_int) {
      _1_main_$pc[0] += *((int *)_1_main_$pc[0]);
    } else {
      _1_main_$pc[0] += 4;
    }
    (_1_main_$sp[0]) --;
    break;
    }
  }
}
}
void megaInit(void) 
{ 


  {

}
}
